### ISSUE TITLE
Responsiveness issue

### ISSUE THREAD

**Issue by Murat-Karakaya** [Frnt-End/Weather-App-React#1]
When I set the height of this website to about 320px (and keep the width same). The problem becomes very visible: Span with the class header owerlaps with div with the class tabs-wrap. To fix this issue maybe set the top margin of the span with the class header to 10px. to make sure it never owerlaps.

**Comment by Frnt-End** [comment]
Some of the elements was positioned using the 'position' property instead of using **flex-box**. its fixed now, thank you!
